.

diff --git a/current/kak/.config/kak/kakrc b/current/kak/.config/kak/kakrc
--- a/current/kak/.config/kak/kakrc
+++ b/current/kak/.config/kak/kakrc
@@ -1,6 +1,4 @@
 source ~/.config/kak/colors/gruvbox.kak
-source ~/.config/kak/filetype/rust.kak
-source ~/.config/kak/editorconfig.kak
 
 # Window focus.
 # ‾‾‾‾‾‾‾‾‾‾‾‾‾
@@ -34,23 +32,63 @@ hook global FocusOut .* %{
 # Autowrap.
 # ‾‾‾‾‾‾‾‾‾
 
-declare-option int autowrap_column
-set-option global autowrap_column 80
-# set-option global autowrap_fmtcmd 'kakconf wrap-text -w %c'
-# set-option global autowrap_format_paragraph yes
+declare-option -docstring "maximum amount of characters per line, after which a newline character will be inserted" \
+    int autowrap_column 80
 
-# hook global WinSetOption filetype=(asciidoc|markdown) %{
-#     autowrap-enable
-#     hook -once window WinSetOption filetype=(?!asciidoc)(?!markdown).* %{
-#         autowrap-disable
-#     }
-# }
+define-command -hidden autowrap-cursor %{
+    evaluate-commands -save-regs '/"|^@m' %{
+        try %{
+            # If the line isn't too long, do nothing.
+            execute-keys -draft "<a-x><a-k>^[^\n]{%opt{autowrap_column},}[^\n]<ret>"
 
-define-command wrap -docstring "Wrap comment to fit %opt{autowrap_column} chars for %%opt{filetype}" %{
-    execute-keys "| kakconf wrap-text -f %opt{filetype} -w %opt{autowrap_column}<ret>"
+            try %{
+                set-register m "%val{selections_desc}"
+
+                # If we're adding characters past the limit, just wrap them around.
+                execute-keys -draft "<a-h><a-k>.{%opt{autowrap_column}}\h*[^\s]*<ret>1s(\h+)[^\h]*\z<ret>c<ret>"
+            } catch %{
+                # If we're adding characters in the middle of a sentence, use
+                # the `fmtcmd` command to wrap the entire paragraph.
+                evaluate-commands %sh{
+                    printf %s "
+                        evaluate-commands -draft %{
+                            execute-keys '<a-]>p<a-x><a-j>|kakconf wrap-text -w $kak_opt_autowrap_column<ret>'
+                            try %{ execute-keys s\h+$<ret> d }
+                        }
+                        select '${kak_main_reg_m}'
+                    "
+                }
+            }
+        }
+    }
 }
 
-map global normal '=' ': wrap<ret>' -docstring "wrap comment to fit %opt{autowrap_column} chars for %%opt{filetype}"
+define-command autowrap-enable -docstring "Automatically wrap the lines in which characters are inserted" %{
+    hook -group autowrap window InsertChar [^\n] autowrap-cursor
+}
+
+define-command autowrap-disable -docstring "Disable automatic line wrapping" %{
+    remove-hooks window autowrap
+}
+
+hook global WinSetOption filetype=(asciidoc|markdown) %{
+    autowrap-enable
+    hook -once window WinSetOption filetype=(?!asciidoc)(?!markdown).* %{
+        autowrap-disable
+    }
+}
+
+define-command wrap-text -docstring "Wrap text to fit %opt{autowrap_column} chars for %%opt{filetype}" %{
+    execute-keys %sh{
+        if [ "$kak_opt_filetype" ]; then
+            echo "| kakconf wrap-text -f %opt{filetype} -w %opt{autowrap_column}<ret>"
+        else
+            echo "| kakconf wrap-text -w %opt{autowrap_column}<ret>"
+        fi
+    }
+}
+
+map global normal '=' ': wrap-text<ret>' -docstring "wrap text to fit %opt{autowrap_column} chars for %%opt{filetype}"
 
 # Appearance.
 # ‾‾‾‾‾‾‾‾‾‾‾
@@ -74,13 +112,10 @@ set-option global modelinefmt '%val{cursor_line}:%val{cursor_column}:%val{buf_li
 
 set-option global tabstop 4
 set-option global indentwidth 4
-# set-option global grepcmd 'rg -L --hidden --with-filename --column'
 set-option global autoreload no
 
 define-command pwd -docstring 'Print the current working directory' %{
-    evaluate-commands %sh{
-        echo "echo $PWD"
-    }
+    echo %sh{ echo "$PWD" }
 }
 
 define-command put-cursors -params 1.. -docstring 'Put cursors at specific line numbers' %{
@@ -311,9 +346,9 @@ define-command xsel-replace -docstring "Replace all selections with X11 clipboar
 define-command xsel-paste -params 1..2 -docstring 'Paste from X11 clipboard' %{
     evaluate-commands %sh{
         if [ "$2" ]; then
-            kakconf paste $1 $2
+            kakconf paste "$1" "$2"
         else
-            kakconf paste $1
+            kakconf paste "$1"
         fi
     }
 }
@@ -367,14 +402,25 @@ map global user A ': enter-user-mode arithmetic<ret>' -docstring 'arithmetic mod
 map global arithmetic j ': decnumber<ret>' -docstring 'decrement number'
 map global arithmetic k ': incnumber<ret>' -docstring 'increment number'
 
-# Editor config integration.
-# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
+# EditorConfig.
+# ‾‾‾‾‾‾‾‾‾‾‾‾‾
 
+hook global BufCreate .*[.](editorconfig) %{
+    set-option buffer filetype ini
+    set-option buffer static_words indent_style indent_size tab_width \
+        end_of_line charset insert_final_newline trim_trailing_whitespace root \
+        latin1 utf-8 utf-8-bom utf-16be utf-16le lf cr crlf unset space tab \
+        max_line_length
+}
+
+define-command editorconfig-load -params ..1 -docstring "editorconfig-load [file]: set formatting behavior according to editorconfig" %{
+    evaluate-commands %sh{ kakconf editorconfig -p "${1:-$kak_buffile}" }
+}
 hook global BufOpenFile .* %{ editorconfig-load }
 hook global BufNewFile .* %{ editorconfig-load }
 
-# Highlight the word under the cursor.
-# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
+# Highlight word under cursor.
+# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 # Taken from mawww's dotfiles.
 
 # set-face global CurrentWord "default,%opt{gruvbox_bg2}"
@@ -414,14 +460,148 @@ hook global InsertDelete ' ' %{
 
 hook global BufWritePre .* %{
     try %{
-        evaluate-commands %sh{
+        execute-keys -draft %sh{
             case "$kak_opt_filetype" in
-            asciidoc|markdown) exit ;;
-            *) echo execute-keys -draft '%s\h+$<ret>d' ;;
+                markdown) ;;
+                *) echo '%s\h+$<ret>d' ;;
             esac
         }
     }
 }
+
+# Comments.
+# ‾‾‾‾‾‾‾‾‾
+
+# Line comments.
+declare-option -docstring "characters inserted at the beginning of a commented line" \
+    str comment_line '#'
+
+# Block comments.
+declare-option -docstring "characters inserted before a commented block" \
+    str comment_block_begin
+declare-option -docstring "characters inserted after a commented block" \
+    str comment_block_end
+
+# Default comments for all languages.
+hook global BufSetOption filetype=asciidoc %{
+    set-option buffer comment_line '//'
+    set-option buffer comment_block_begin '////'
+    set-option buffer comment_block_end '////'
+}
+
+hook global BufSetOption filetype=(c|cpp|dart|javascript|rust|typescript) %{
+    set-option buffer comment_line '//'
+    set-option buffer comment_block_begin '/*'
+    set-option buffer comment_block_end '*/'
+}
+
+hook global BufSetOption filetype=css %{
+    set-option buffer comment_line ''
+    set-option buffer comment_block_begin '/*'
+    set-option buffer comment_block_end '*/'
+}
+
+hook global BufSetOption filetype=ini %{
+    set-option buffer comment_line ';'
+}
+
+hook global BufSetOption filetype=(html|xml) %{
+    set-option buffer comment_line ''
+    set-option buffer comment_block_begin '<!--'
+    set-option buffer comment_block_end '-->'
+}
+
+hook global BufSetOption filetype=latex %{
+    set-option buffer comment_line '%'
+}
+
+hook global BufSetOption filetype=markdown %{
+    set-option buffer comment_line ''
+    set-option buffer comment_block_begin '[//]: # "'
+    set-option buffer comment_block_end '"'
+}
+
+hook global BufSetOption filetype=zig %{
+    set-option buffer comment_line '//'
+}
+
+hook global BufSetOption filetype=python %{
+    set-option buffer comment_block_begin "'''"
+    set-option buffer comment_block_end "'''"
+}
+
+define-command extend-selections-left -docstring 'extend selections to the left to align with the leftmost selected column' %{
+    evaluate-commands %sh{
+        seldesc=$(kakconf extend-selections -d left -s "$kak_selections_desc")
+        echo select "$seldesc"
+    }
+}
+
+define-command comment-block -docstring '(un)comment selections using block comments' %{
+    evaluate-commands %sh{
+        if [ -z "${kak_opt_comment_block_begin}" ] || [ -z "${kak_opt_comment_block_end}" ]; then
+            echo "fail \"The 'comment_block' options are empty, could not comment the selection\""
+        fi
+    }
+
+    evaluate-commands -save-regs '"/' -draft %{
+        # Keep non-empty selections.
+        execute-keys <a-K>\A\s*\z<ret>
+
+        try %{
+            # Assert that the selection has been commented.
+            set-register / "\A\Q%opt{comment_block_begin}\E.*\Q%opt{comment_block_end}\E\n*\z"
+            execute-keys "s<ret>"
+            # Uncomment it.
+            set-register / "\A\Q%opt{comment_block_begin}\E|\Q%opt{comment_block_end}\E\n*\z"
+            execute-keys s<ret>d
+        } catch %{
+            # Comment the selection.
+            set-register '"' "%opt{comment_block_begin}"
+            execute-keys P
+            set-register '"' "%opt{comment_block_end}"
+            execute-keys p
+        }
+    }
+}
+
+define-command comment-line -docstring '(un)comment selected lines using line comments' %{
+    evaluate-commands %sh{
+        if [ -z "${kak_opt_comment_line}" ]; then
+            echo "fail \"The 'comment_line' option is empty, could not comment the line\""
+        fi
+    }
+
+    evaluate-commands -save-regs '"/' -draft %{
+        # Select the content of the lines, without indentation.
+        execute-keys <a-s>gi<a-l>
+
+        try %{
+            # Keep non-empty lines.
+            execute-keys <a-K>\A\s*\z<ret>
+        }
+
+        try %{
+            set-register / "\A\Q%opt{comment_line}\E\h?"
+
+            try %{
+                # See if there are any uncommented lines in the selection.
+                execute-keys -draft <a-K><ret>
+
+                # There are uncommented lines, so comment everything.
+                set-register '"' "%opt{comment_line} "
+                extend-selections-left
+                execute-keys P
+            } catch %{
+                # All lines were commented, so uncomment everything.
+                execute-keys s<ret>d
+            }
+        }
+    }
+}
+
+map global normal '#' ': comment-line<ret>' -docstring '(un)comment selected lines using line comments'
+map global normal '<a-#>' ': comment-block<ret>' -docstring '(un)comment selections using block comments'
 
 # Custom mappings.
 # ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
@@ -430,7 +610,6 @@ map global normal '<space>' ',' -docstring 'leader key'
 map global normal ',' '<space>' -docstring 'remove all selections except main'
 map global normal '<a-,>' '<a-space>' -docstring 'remove the main selection'
 
-map global normal '#' ': comment-line<ret>' -docstring 'comment/uncomment selection'
 map global user '<space>' '/(?i)' -docstring 'search (case insensitive)'
 
 # Means <c-j>.
@@ -540,33 +719,33 @@ map global surround-lock } ': surround-pair { }<ret>' -docstring 'surround with 
 # LSP.
 # ‾‾‾‾
 
-evaluate-commands %sh{
-    kak-lsp --kakoune -s "$kak_session"
-}
-
-set-option global lsp_diagnostic_line_error_sign '█'
-# set-option global lsp_diagnostic_line_warning_sign '▓'
-set-option global lsp_diagnostic_line_warning_sign '▒'
-set-option global lsp_hover_anchor true
-set-option global lsp_insert_spaces true
-set-option global lsp_auto_highlight_references true
-
-set-face global DiagnosticError "default+u"
-set-face global DiagnosticWarning "default+u"
-set-face global LineFlagErrors "%opt{gruvbox_c9_red}"
-
-map global user 'l' ': enter-user-mode lsp<ret>' -docstring 'LSP mode'
-map global normal '<c-f>' ': lsp-hover<ret>' -docstring 'show info for current position'
-map global lsp 'R' ': lsp-rename-prompt<ret>' -docstring 'rename symbol under the main cursor (prompt for a new name)'
-
-hook global WinSetOption filetype=(rust-custom|python|sh|dart) %{
-    lsp-enable-window
-}
-
-define-command lsp-restart -docstring 'Restart kak-lsp session' %{
-    lsp-stop
-    lsp-start
-}
+# evaluate-commands %sh{
+#     kak-lsp --kakoune -s "$kak_session"
+# }
+# 
+# set-option global lsp_diagnostic_line_error_sign '█'
+# # set-option global lsp_diagnostic_line_warning_sign '▓'
+# set-option global lsp_diagnostic_line_warning_sign '▒'
+# set-option global lsp_hover_anchor true
+# set-option global lsp_insert_spaces true
+# set-option global lsp_auto_highlight_references true
+# 
+# set-face global DiagnosticError "default+u"
+# set-face global DiagnosticWarning "default+u"
+# set-face global LineFlagErrors "%opt{gruvbox_c9_red}"
+# 
+# map global user 'l' ': enter-user-mode lsp<ret>' -docstring 'LSP mode'
+# map global normal '<c-f>' ': lsp-hover<ret>' -docstring 'show info for current position'
+# map global lsp 'R' ': lsp-rename-prompt<ret>' -docstring 'rename symbol under the main cursor (prompt for a new name)'
+# 
+# hook global WinSetOption filetype=(rust-custom|python|sh|dart) %{
+#     lsp-enable-window
+# }
+# 
+# define-command lsp-restart -docstring 'Restart kak-lsp session' %{
+#     lsp-stop
+#     lsp-start
+# }
 
 # Custom objects.
 # ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
@@ -574,28 +753,66 @@ define-command lsp-restart -docstring 'Restart kak-lsp session' %{
 # Taken from mawww's dotfiles.
 map -docstring "XML tag object" global object t %{c<lt>([\w.]+)\b[^>]*?(?<lt>!/)>,<lt>/([\w.]+)\b[^>]*?(?<lt>!/)><ret>}
 
-# Language configuration.
-# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
+# Format.
+# ‾‾‾‾‾‾‾
 
-hook global WinSetOption filetype=rust-custom %{
-    set-option buffer formatcmd 'rustfmt'
-    hook buffer BufWritePre .* %{format}
-    set-option buffer lsp_server_configuration rust.clippy_preference="on"
+declare-option -docstring "shell command used for the 'format-selections' and 'format-buffer' commands" \
+    str formatcmd
+
+define-command format-buffer -docstring "Format the contents of the buffer" %{
+    evaluate-commands -draft %{
+        execute-keys '%'
+        format-selections
+    }
+}
+
+define-command format-selections -docstring "Format the selections individually" %{
+    evaluate-commands %sh{
+        if [ -z "${kak_opt_formatcmd}" ]; then
+            echo "fail 'The option ''formatcmd'' must be set'"
+        fi
+    }
+    evaluate-commands -draft -no-hooks -save-regs '|' %{
+        set-register '|' %{
+            format_in="$(mktemp "${TMPDIR:-/tmp}"/kak-formatter.XXXXXX)"
+            format_out="$(mktemp "${TMPDIR:-/tmp}"/kak-formatter.XXXXXX)"
+
+            cat >"$format_in"
+            eval "$kak_opt_formatcmd" <"$format_in" >"$format_out"
+            if [ $? -eq 0 ]; then
+                cat "$format_out"
+            else
+                printf 'eval -client %s %%{ fail formatter returned an error %s }\n' "$kak_client" "$?" | kak -p "$kak_session"
+                cat "$format_in"
+            fi
+            rm -f "$format_in" "$format_out"
+        }
+        execute-keys '|<ret>'
+    }
+}
+
+# Languages.
+# ‾‾‾‾‾‾‾‾‾‾
+
+hook global WinSetOption filetype=rust %{
+    set-option buffer formatcmd 'rustfmt --config "edition=2018"'
+    hook buffer BufWritePre .* %{format-buffer}
+    # set-option buffer lsp_server_configuration rust.clippy_preference="on"
 }
 
 hook global WinSetOption filetype=zig %{
     set-option buffer formatcmd 'zig fmt --stdin'
-    hook buffer BufWritePre .* %{format}
+    hook buffer BufWritePre .* %{format-buffer}
 }
 
 hook global WinSetOption filetype=python %{
     set-option buffer formatcmd 'autopep8 -'
-    hook buffer BufWritePre .* %{format}
+    hook buffer BufWritePre .* %{format-buffer}
 }
 
 hook global WinSetOption filetype=cpp %{
     set-option buffer formatcmd 'clang-format'
-    hook buffer BufWritePre .* %{format}
+    hook buffer BufWritePre .* %{format-buffer}
 }
 
 hook global WinSetOption filetype=grep %{
@@ -606,30 +823,22 @@ hook global WinSetOption filetype=grep %{
 
 hook global WinSetOption filetype=html %{
     set-option buffer formatcmd 'prettier --parser=html'
-    hook buffer BufWritePre .* %{format}
+    hook buffer BufWritePre .* %{format-buffer}
 }
 
 hook global WinSetOption filetype=typescript %{
     set-option buffer formatcmd 'prettier --parser=typescript'
-    hook buffer BufWritePre .* %{format}
+    hook buffer BufWritePre .* %{format-buffer}
 }
 
 hook global WinSetOption filetype=css %{
     set-option buffer formatcmd 'prettier --parser=css'
-    hook buffer BufWritePre .* %{format}
+    hook buffer BufWritePre .* %{format-buffer}
 }
 
 hook global WinSetOption filetype=json %{
     set-option buffer formatcmd 'jq .'
-    hook buffer BufWritePre .* %{format}
-}
-
-hook global BufCreate '.*\.mk$' %{
-    set-option buffer filetype makefile
-}
-
-hook global BufCreate '.*\.cs$' %{
-    set-option buffer filetype csharp
+    hook buffer BufWritePre .* %{format-buffer}
 }
 
 hook global BufCreate '.*\.config/polybar/config$' %{
